2015-06-17 00:48:40+0800 [scrapy] INFO: Scrapy 0.24.6 started (bot: wa)
2015-06-17 00:48:40+0800 [scrapy] INFO: Optional features available: ssl, http11, django
2015-06-17 00:48:40+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'wa.spiders', 'SPIDER_MODULES': ['wa.spiders'], 'COOKIES_ENABLED': False, 'BOT_NAME': 'wa'}
2015-06-17 00:48:40+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2015-06-17 00:48:40+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-06-17 00:48:40+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-06-17 00:48:40+0800 [scrapy] INFO: Enabled item pipelines: WaPipeline
2015-06-17 00:48:40+0800 [wa] INFO: Spider opened
2015-06-17 00:48:40+0800 [wa] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-06-17 00:48:40+0800 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-06-17 00:48:40+0800 [scrapy] DEBUG: Web service listening on 127.0.0.1:6080
2015-06-17 00:48:40+0800 [wa] DEBUG: Crawled (200) <GET http://tieba.baidu.com/f?kw=%E6%98%8E%E6%98%9F%E5%90%8C%E6%AC%BE&ie=utf-8&pn=0> (referer: None)
/root/stczwd/Scrapy/wa/wa/pipelines.py:54: Warning: Field 'starId' doesn't have a default value
  cur.execute(sql)
/root/stczwd/Scrapy/wa/wa/pipelines.py:54: Warning: Field 'starName' doesn't have a default value
  cur.execute(sql)
/root/stczwd/Scrapy/wa/wa/pipelines.py:54: Warning: Field 'quizeState' doesn't have a default value
  cur.execute(sql)
/root/stczwd/Scrapy/wa/wa/pipelines.py:54: Warning: Field 'quizePic' doesn't have a default value
  cur.execute(sql)
/root/stczwd/Scrapy/wa/wa/pipelines.py:54: Warning: Field 'quizeType' doesn't have a default value
  cur.execute(sql)
2015-06-17 00:48:40+0800 [wa] DEBUG: Scraped from <200 http://tieba.baidu.com/f?kw=%E6%98%8E%E6%98%9F%E5%90%8C%E6%AC%BE&ie=utf-8&pn=0>
	{'quizeContent': '[[]]', 'quizeTitle': []}
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\x9c\\x80\\xe5\\xa5\\xbd\\xe7\\x94\\xa9TB\\xe9\\x93\\xbe\\xe6\\x8e\\xa5 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\xbc\xa0\xe8\xb4\xa4\xe8\x83\x9c\xe2\x80\x9c\xe4\xbd\xa0\xe6\x98\xaf\xe6\x88\x91\xe7\x9a\x84\xe7\xac\xac\xe4\xb8\x80\xe6\xac\xa1\xe2\x80\x9d\xe6\x89\x80\xe6\x9c\x89\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\x9c\\x80\\xe5\\xa5\\xbd\\xe7\\x94\\xa9TB\\xe9\\x93\\xbe\\xe6\\x8e\\xa5 ', '\\r\\n\\t\\t', '\\' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\xb1\\x82\\xe6\\x9f\\xb4\\xe8\\x94\\x9a\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe8\\xa3\\x99\\xe5\\xad\\x90~~\\xe5\\x9b\\xbe\\xe6\\xa1\\x88\\xe4\\xb8\\x8d\\xe4\\xb8\\x80\\xe6\\xa0\\xb7\\xe9\\x83\\xbd\\xe5\\x8f\\xaf\\xe4\\xbb\\xa5\\xef\\xbc\\x8c\\xe6\\x88\\x91\\xe8\\xa6\\x81\\xe5\\x90\\x8c\\xe6\\x84\\x8f\\xe7\\x9a\\x84\\xe6\\xac\\xbe\\xe5\\xbc\\x8f ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe6\x9f\xb4\xe8\x94\x9a\xe5\x90\x8c\xe6\xac\xbe\xe8\xa3\x99\xe5\xad\x90~~']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\xb1\\x82\\xe6\\x9f\\xb4\\xe8\\x94\\x9a\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe8\\xa3\\x99\\xe5\\xad' at line 1")
	
2015-06-17 00:48:40+0800 [wa] DEBUG: Scraped from <200 http://tieba.baidu.com/f?kw=%E6%98%8E%E6%98%9F%E5%90%8C%E6%AC%BE&ie=utf-8&pn=0>
	{'quizeContent': '[[]]', 'quizeTitle': []}
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe9\x9c\x8d\xe6\x80\x9d\xe7\x87\x95\xe8\xbf\x99\xe6\xac\xbe\xe5\xa4\x96\xe5\xa5\x97']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe7\\xae\\x80\\xe5\\x8d\\x95\\xe7\\xb2\\x97\\xe6\\x9a\\xb4\\xe7\\x9b\\xb4\\xe6\\x8e\\xa5\\xe4\\xb8\\x8a\\xe5\\x9b\\xbe\\xef\\xbc\\x8c\\xe5\\x90\\x84\\xe4\\xbd\\x8d\\xe5\\xa4\\xa7\\xe7\\xa5\\x9e\\xe5\\xb8\\xae\\xe4\\xb8\\xaa\\xe5\\xbf\\x99\\xe6\\x89\\xbe\\xe6\\x89\\xbe ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe3\x80\x90\xe5\x90\x8c\xe6\xac\xbe\xe3\x80\x91[2015.5.21]\xe5\xb8\xae\xe5\xbf\x99\xe6\x89\xbe\xe4\xb8\x80\xe4\xbb\xb6T\xe6\x81\xa4\xef\xbc\x8c\xe8\xb0\xa2\xe8\xb0\xa2']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe7\\xae\\x80\\xe5\\x8d\\x95\\xe7\\xb2\\x97\\xe6\\x9a\\xb4\\xe7\\x9b\\xb4\\xe6\\x8e\\xa5\\xe4\\xb8' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe5\\xa7\\x9a\\xe8\\xbf\\xaa\\xef\\xbc\\x8c\\xe6\\x9d\\xa8\\xe5\\xb9\\x82\\xef\\xbc\\x8c\\xe9\\xab\\x98\\xe5\\x9c\\x86\\xe5\\x9c\\x86\\xe7\\xad\\x89\\xe5\\x90\\x8c\\xe6\\xac\\xbe', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe5\x90\x84\xe7\xa7\x8d\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe5\\xa7\\x9a\\xe8\\xbf\\xaa\\xef\\xbc\\x8c\\xe6\\x9d\\xa8\\xe5\\xb9\\x82\\xef\\xbc\\x8c\\xe9\\xab' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\xb1\\x82\\xe5\\x8a\\xa9\\xef\\xbc\\x81\\xe8\\xa3\\x99\\xe5\\xad\\x90\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xef\\xbc\\x81 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\x8a\xa9\xef\xbc\x81\xe8\xa3\x99\xe5\xad\x90\xe5\x90\x8c\xe6\xac\xbe\xef\xbc\x81']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\xb1\\x82\\xe5\\x8a\\xa9\\xef\\xbc\\x81\\xe8\\xa3\\x99\\xe5\\xad\\x90\\xe5\\x90\\x8c\\xe6\\xac' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x9d\x8e\xe6\x99\xa8\xef\xbc\x8c\xe6\x9d\xa8\xe5\xb9\x82\xef\xbc\x8c\xe4\xba\x95\xe6\x9f\x8f\xe7\x84\xb6\xef\xbc\x8c\xe6\xb1\xa0\xe6\x98\x8c\xe6\x97\xad\xe7\xad\x89\xe7\xad\x89\xe6\xac\xa7\xe7\xbe\x8e\xe5\xa4\xa7\xe7\x89\x8c\xe5\x90\x8c\xe6\xac\xbe\xe7\x99\xbe\xe6\x90\xad\xe6\x83\x85\xe4\xbe\xa3\xe9\x9e\x8b']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['weixin\\xe5\\x8f\\xb7ZZA703\\xe3\\x80\\x82\\xe4\\xb8\\xbb\\xe8\\x90\\xa5 nb ad nike aj [ATHLETIC SHOE] \\xe5\\x90\\x8d\\xe7\\x89\\x8c\\xe5\\x8c\\x85\\xe5\\x8c\\x85 [HANDBAG]\\xef\\xbc\\x8c\\xe5\\x8e\\x9f\\xe5\\x8e\\x82\\xef\\xbc\\x8c\\xe5\\x8f\\xaa\\xe5\\x81\\x9a\\xe7\\xb2\\xbe\\xe4\\xbb\\xbf\\xe6\\xad\\xa3\\xe5\\x93\\x81\\xef\\xbc\\x8c\\xe8\\xaf\\x9a\\xe6\\x8b\\x9b\\xe4\\xbb\\xa3\\xe7\\x90\\x86', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe4\xb8\x93\xe6\x9f\x9c\xe7\x9a\x84\xe8\xb4\xa8\xe9\x87\x8f\xef\xbc\x8c\xe5\xb9\xb3\xe6\xb0\x91\xe7\x9a\x84\xe4\xbb\xb7\xe6\xa0\xbc\xe3\x80\x82']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'weixin\\xe5\\x8f\\xb7ZZA703\\xe3\\x80\\x82\\xe4\\xb8\\xbb\\xe8\\x90\\xa5 nb ad nike aj [ATHL' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\x98\\xa8\\xe5\\xa4\\xa9\\xe8\\xbf\\x98\\xe5\\xa5\\xbd\\xe5\\xa5\\xbd\\xe7\\x9a\\x84\\xef\\xbc\\x8c\\xe4\\xb8\\x80\\xe8\\xa7\\x89\\xe9\\x86\\x92\\xe6\\x9d\\xa5\\xef\\xbc\\x8c\\xe5\\xb8\\x96\\xe5\\xad\\x90\\xe6\\x80\\x8e\\xe4\\xb9\\x88\\xe9\\x83\\xbd\\xe4\\xb8\\x8d\\xe8\\xa7\\x81\\xe4\\xba\\x86\\xe5\\x95\\x8a\\xef\\xbc\\x81']]",
	 'quizeTitle': ['\xe6\x80\x8e\xe4\xb9\x88\xe9\x87\x8c\xe9\x9d\xa2\xe7\x9a\x84\xe5\xb8\x96\xe5\xad\x90\xe8\xa2\xab\xe5\x88\xa0\xe5\x85\x89\xe4\xba\x86\xe5\x95\x8a\xc2\xb7']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\x98\\xa8\\xe5\\xa4\\xa9\\xe8\\xbf\\x98\\xe5\\xa5\\xbd\\xe5\\xa5\\xbd\\xe7\\x9a\\x84\\xef\\xbc' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\x9d\\xa5\\xe5\\x9b\\xbe\\xe8\\x87\\xaa\\xe5\\xae\\x9a\\xe4\\xb9\\x89\\xe5\\xae\\x9a\\xe5\\x88\\xb6:T\\xe6\\x81\\xa4\\xef\\xbc\\x8c\\xe5\\xb0\\x8f\\xe9\\xa3\\x8e\\xe6\\x89\\x87\\xef\\xbc\\x8c\\xe6\\x89\\x8b\\xe6\\x9c\\xba\\xe5\\xa3\\xb3\\xef\\xbc\\x8c\\xe5\\x8f\\x98\\xe8\\x89\\xb2\\xe6\\x9d\\xaf\\xef\\xbc\\x8c\\xe5\\x85\\x85\\xe7\\x94\\xb5\\xe5\\xae\\x9d\\xef\\xbc\\x8c\\xe6\\x89\\x93\\xe7\\x81\\xab\\xe6\\x9c\\xba\\xef\\xbc\\x8c\\xe6\\xb0\\xb4\\xe6\\x99\\xb6\\xe7\\x9b\\xb8\\xe6\\xa1\\x86\\xef\\xbc\\x8c\\xe6\\x8a\\xb1\\xe6\\x9e\\x95\\xef\\xbc\\x8c\\xe8\\xa6\\x81\\xe7\\x9a\\x84\\xe7\\xa7\\x81\\xe6\\x88\\x91']]",
	 'quizeTitle': ['\xe6\x9d\xa5\xe5\x9b\xbe\xe8\x87\xaa\xe5\xae\x9a\xe4\xb9\x89\xe5\xae\x9a\xe5\x88\xb6:T\xe6\x81\xa4\xef\xbc\x8c\xe5\xb0\x8f\xe9\xa3\x8e\xe6\x89\x87\xef\xbc\x8c']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\x9d\\xa5\\xe5\\x9b\\xbe\\xe8\\x87\\xaa\\xe5\\xae\\x9a\\xe4\\xb9\\x89\\xe5\\xae\\x9a\\xe5\\x88' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\xb1\\x82\\xe6\\x9d\\x8e\\xe6\\xb5\\xb7\\xe5\\xa8\\x9c\\xe6\\xa0\\xbc\\xe5\\xad\\x90\\xe5\\xa5\\x97\\xe8\\xa3\\x85\\xe8\\xa3\\x99\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe5\\x95\\x8a\\xef\\xbc\\x81\\xef\\xbc\\x81\\xef\\xbc\\x81\\xef\\xbc\\x81 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\x90\x8c\xe6\xac\xbe\xe5\x95\x8a\xef\xbc\x81\xef\xbc\x81\xef\xbc\x81\xef\xbc\x81']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\xb1\\x82\\xe6\\x9d\\x8e\\xe6\\xb5\\xb7\\xe5\\xa8\\x9c\\xe6\\xa0\\xbc\\xe5\\xad\\x90\\xe5\\xa5' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe8\\xb0\\x81\\xe6\\x9c\\x89\\xe8\\xbf\\x99\\xe5\\xa5\\x97\\xe8\\xa1\\xa3\\xe6\\x9c\\x8d\\xe9\\x93\\xbe\\xe6\\x8e\\xa5\\xe7\\xbb\\x99\\xe6\\x88\\x91', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['hight school\xe7\xac\xac20\xe9\x9b\x86\xe5\xa5\xb3\xe4\xb8\xbb\xe5\x90\x8c\xe6\xac\xbe\xef\x98\x8d\xef\x98\x8d']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe8\\xb0\\x81\\xe6\\x9c\\x89\\xe8\\xbf\\x99\\xe5\\xa5\\x97\\xe8\\xa1\\xa3\\xe6\\x9c\\x8d\\xe9\\x93' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[[' ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe5\x91\xa8\xe8\xbf\x85\xe5\x90\x8c\xe6\xac\xbe\xe9\x9e\x8b\xef\xbc\x8c\xe6\x8b\x9c\xe6\x89\x98\xe4\xba\x86']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x9d\x8e\xe5\xb0\x8f\xe7\x92\x90\xe7\x9a\x84\xe8\xbf\x99\xe4\xb8\xaa\xe5\x90\x8c\xe6\xac\xbe\xe9\x9e\x8b\xef\x99\x8f']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe9\x85\xb7\xe7\x88\xb8\xe4\xbf\x8f\xe5\xa6\x88\xe5\x90\x8c\xe6\xac\xbe\xe6\x9d\xa5\xe5\x95\xa6']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\xb1\\x82\\xe5\\xb8\\xae\\xe5\\xbf\\x99\\xe6\\x89\\xbe\\xe8\\xbf\\x99\\xe4\\xb8\\xaa\\xe6\\x95\\x8f\\xe9\\x9b\\x85\\xe7\\x9a\\x84\\xe7\\xb2\\x89\\xe8\\x89\\xb2\\xe8\\x83\\x8c\\xe5\\xbf\\x83 \\xe5\\x8f\\xb3\\xe4\\xb8\\x80 \\xe8\\xb0\\xa2\\xe8\\xb0\\xa2 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\xb8\xae\xe5\xbf\x99\xe6\x89\xbe\xe8\xbf\x99\xe4\xb8\xaa\xe6\x95\x8f\xe9\x9b\x85\xe7\x9a\x84\xe7\xb2\x89\xe8\x89\xb2\xe8\x83\x8c\xe5\xbf\x83']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\xb1\\x82\\xe5\\xb8\\xae\\xe5\\xbf\\x99\\xe6\\x89\\xbe\\xe8\\xbf\\x99\\xe4\\xb8\\xaa\\xe6\\x95' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe4\\xbb\\xb7\\xe6\\xa0\\xbc\\xe5\\x85\\xac\\xe9\\x81\\x93\\xef\\xbc\\x81 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x9d\xa5\xe6\x89\xbe\xe6\x89\xbe\xe5\xa4\xa7\xe5\xae\xb6\xe5\xbf\x83\xe6\xb0\xb4\xe7\x9a\x84\xe5\x90\x8c\xe6\xac\xbe\xe5\x90\xa7\xef\xbc\x81']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe4\\xbb\\xb7\\xe6\\xa0\\xbc\\xe5\\x85\\xac\\xe9\\x81\\x93\\xef\\xbc\\x81 ', '\\r\\n\\t\\t', '\\r\\' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x89\xbe\xe6\x89\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['V\xe6\x9d\x8f yn518888']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe7\\x94\\xb7\\xe7\\xa5\\x9e\\xe9\\x95\\x87\\xe6\\xa5\\xbc\\xef\\xbc\\x81EXO\\xe6\\xb2\\xa1\\xe9\\x94\\x99\\xef\\xbc\\x81\\xef\\xbc\\x81\\xe8\\xbf\\x99\\xe4\\xb8\\xaa\\xe5\\xb0\\xb1\\xe6\\x98\\xaf\\xe6\\x97\\xa0\\xe6\\x95\\xb0\\xe6\\xac\\xa1\\xe5\\x87\\xba\\xe7\\x8e\\xb0\\xe5\\x9c\\xa8EXO SHOW TIME \\xe9\\x87\\x8c\\xe7\\x9a\\x84\\xe7\\xbb\\xb4\\xe7\\x94\\x9f\\xe7\\xb4\\xa0c\\xe5\\x86\\xb2\\xe5\\x89\\x82\\xef\\xbc\\x81\\xef\\xbc\\x81\\xe5\\x8e\\xbb\\xe5\\x8d\\x97\\xe5\\xb1\\xb1\\xe5\\xa1\\x94\\xe9\\x82\\xa3\\xe6\\xac\\xa1\\xef\\xbc\\x81\\xef\\xbc\\x81\\xe4\\xbb\\x96\\xe4\\xbb\\xac\\xe5\\x9c\\xa8\\xe4\\xbe\\xbf\\xe5\\x88\\xa9\\xe5\\xba\\x97\\xe4\\xb9\\xb0\\xe7\\x9a\\x84\\xe5\\xb0\\xb1\\xe6\\x98\\xaf\\xe8\\xbf\\x99\\xe4\\xb8\\xaa\\xe5\\x93\\xa6[\\xe7\\x8e\\xab\\xe7\\x91\\xb0][\\xe7\\x8e\\xab\\xe7\\x91\\xb0]\\xe6\\x88\\x91\\xe4\\xbb\\x8e\\xe9\\x9f\\xa9\\xe5\\x9b\\xbd\\xe5\\xae\\x9a\\xe5\\xa4\\x9f', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe9\xb9\xbf\xe5\x93\xa5\xe9\xa5\xad\xe4\xbb\xac\xe7\x9a\x84\xe7\xa6\x8f\xe5\x88\xa9\xef\xbc\x81\xef\xbc\x81\xef\xbc\x81']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe7\\x94\\xb7\\xe7\\xa5\\x9e\\xe9\\x95\\x87\\xe6\\xa5\\xbc\\xef\\xbc\\x81EXO\\xe6\\xb2\\xa1\\xe9\\' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe6\\x83\\xb3\\xe5\\x81\\x9aDaiLI \\xe6\\x88\\x96\\xe8\\x80\\x85JiaNeng \\xe7\\x9a\\x84\\xe8\\x81\\x94\\xe7\\xb3\\xbb\\xe6\\x88\\x91']]",
	 'quizeTitle': ['EXO    TFboys   FX']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe6\\x83\\xb3\\xe5\\x81\\x9aDaiLI \\xe6\\x88\\x96\\xe8\\x80\\x85Ji' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe9\\x83\\x91\\xe7\\xa7\\x80\\xe6\\x99\\xb6']]",
	 'quizeTitle': ['\xe9\x83\x91\xe7\xa7\x80\xe6\x99\xb6']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe9\\x83\\x91\\xe7\\xa7\\x80\\xe6\\x99\\xb6']]')' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\x9c\\x80\\xe5\\xa5\\xbd\\xe6\\x98\\xaf\\xe5\\x8d\\x96FX.EXO.TFBOYS\\xe7\\x9a\\x84\\xe5\\x90\\x8c\\xe6\\xac\\xbe']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\x81\x9a\xe4\xbb\xa3\xe7\x90\x86']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\x9c\\x80\\xe5\\xa5\\xbd\\xe6\\x98\\xaf\\xe5\\x8d\\x96FX.EXO.TFBOYS\\xe7\\x9a\\x84\\xe5\\x9' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe8\\xa1\\x8c\\xe6\\x98\\x9f\\xe9\\xa5\\xad\\xe5\\xbf\\xab\\xe6\\x9d\\xa5\\xef\\xbc\\x8c\\xe5\\x85\\xb6\\xe5\\xae\\x9e\\xe6\\x88\\x91\\xe4\\xb9\\x9f\\xe6\\x98\\xaf \\xe5\\xa4\\xa9\\xe7\\x84\\xb6\\xe9\\xbb\\x91\\xe7\\x8e\\x9b\\xe7\\x91\\x99 925\\xe7\\xba\\xaf\\xe9\\x93\\xb6\\xe5\\x85\\x8b\\xe7\\xbd\\x97\\xe5\\xbf\\x83\\xe6\\x89\\x8b\\xe9\\x93\\xbe \\xe6\\x9c\\x89\\xe6\\x83\\x85\\xe4\\xbe\\xa3\\xe6\\xac\\xbe ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['EXO\xe6\x88\x90\xe5\x91\x98\xe6\x9c\xb4\xe7\x81\xbf\xe7\x83\x88\xe5\x90\x8c\xe6\xac\xbe\xe6\x89\x8b\xe9\x93\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe8\\xa1\\x8c\\xe6\\x98\\x9f\\xe9\\xa5\\xad\\xe5\\xbf\\xab\\xe6\\x9d\\xa5\\xef\\xbc\\x8c\\xe5\\x85' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe8\\x90\\x8c\\xe8\\x90\\x8c\\xe5\\x93\\x92\\xe7\\xab\\xa5\\xe6\\x98\\x9f\\xe5\\x85\\x81\\xe7\\xbb\\x92QQ1512395726\\xef\\xbc\\x8c\\xe4\\xb8\\x8d\\xe7\\x88\\xb1\\xe4\\xb8\\x8d\\xe5\\x8a\\xa0\\xe5\\x93\\x92\\xef\\xbc\\x8c\\xe8\\xb0\\xa2\\xe8\\xb0\\xa2\\xe4\\xb9\\x88\\xe4\\xb9\\x88\\xe5\\x93\\x92~\\xe6\\x9c\\x89\\xe6\\x9c\\xba\\xe4\\xbc\\x9a\\xe8\\xaf\\xad\\xe9\\x9f\\xb3\\xe5\\x93\\xa6(\\xc2\\xb4-\\xcf\\x89-`)\\xe5\\xa5\\xb9\\xe5\\x8f\\xaa\\xe6\\x98\\xaf\\xe4\\xb8\\x80\\xe4\\xb8\\xaa\\xe5\\xbe\\x88\\xe5\\x8f\\xaf\\xe7\\x88\\xb1\\xe7\\x9a\\x84\\xe5\\xad\\xa9\\xe5\\xad\\x90\\xef\\xbc\\x8c\\xe8\\xaf\\xb7\\xe4\\xb8\\x8d\\xe8\\xa6\\x81\\xe4\\xbc\\xa4\\xe5\\xae\\xb3\\xe5\\xa5\\xb9\\xe3\\x80\\x82\\xe8\\x90\\x8c\\xe5\\xb9\\xb6\\xe4\\xb8\\x8d\\xe6\\x98\\xaf\\xe5\\xa5\\xb9\\xe7\\x9a\\x84\\xe9\\x94\\x99\\xe3\\x80\\x82', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe8\x90\x8c\xe8\x90\x8c\xe5\x93\x92\xe7\xab\xa5\xe6\x98\x9f\xe4\xbd\xa0\xe7\x88\xb1\xe4\xb9\x88']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe8\\x90\\x8c\\xe8\\x90\\x8c\\xe5\\x93\\x92\\xe7\\xab\\xa5\\xe6\\x98\\x9f\\xe5\\x85\\x81\\xe7\\xbb' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\xb1\\x82\\xe5\\xa4\\xa7\\xe7\\xa5\\x9e\\xe6\\x89\\xbe\\xe5\\xb0\\x8f\\xe6\\xa2\\xa6\\xe8\\xba\\xab\\xe4\\xb8\\x8a\\xe7\\x9a\\x84\\xe8\\xbf\\x99\\xe4\\xbb\\xb6\\xe8\\xa1\\xa3\\xe6\\x9c\\x8d\\xef\\xbc\\x81 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe6\x89\xbe\xe5\xb0\x8f\xe6\xa2\xa6\xe8\xba\xab\xe4\xb8\x8a\xe7\x9a\x84\xe8\xbf\x99\xe4\xbb\xb6\xe8\xa1\xa3\xe6\x9c\x8d\xef\xbc\x81']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\xb1\\x82\\xe5\\xa4\\xa7\\xe7\\xa5\\x9e\\xe6\\x89\\xbe\\xe5\\xb0\\x8f\\xe6\\xa2\\xa6\\xe8\\xba' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\x94\x90\xe5\xab\xa3\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[[' ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe5\xb8\xae\xe5\xbf\x99\xe6\x89\xbe\xe4\xb8\x80\xe4\xb8\x8b\xe5\xbe\x90\xe8\x89\xaf\xe5\x90\x8c\xe6\xac\xbe\xe7\x9a\x84\xe8\xa1\xa3\xe6\x9c\x8d\xef\xbc\x8c\xe6\x8b\x9c\xe6\x89\x98\xe4\xba\x86\xef\xbc\x81\xe8\xb0\xa2\xe8\xb0\xa2\xe5\x95\x8a\xef\xbc\x81']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe5\\x90\\x84\\xe7\\xa7\\x8d\\xe6\\x98\\x8e\\xe6\\x98\\x9f\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe5\\xba\\x94\\xe6\\x9c\\x89\\xe5\\xb0\\xbd\\xe6\\x9c\\x89']]",
	 'quizeTitle': ['\xe6\x98\x8e\xe6\x98\x9f\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe5\\x90\\x84\\xe7\\xa7\\x8d\\xe6\\x98\\x8e\\xe6\\x98\\x9f\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe5\\xba' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['Rt\\xef\\xbc\\x8c\\xe9\\x9f\\xa9\\xe5\\xba\\x9a\\xe7\\x8e\\x8b\\xe4\\xb8\\xbd\\xe5\\x9d\\xa4\\xe6\\x9d\\x8e\\xe6\\x99\\xa8\\xe5\\x90\\x8c\\xe6\\xac\\xbe', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe9\x9f\xa9\xe5\xba\x9a\xe7\xad\x89\xe6\x98\x8e\xe6\x98\x9f\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Rt\\xef\\xbc\\x8c\\xe9\\x9f\\xa9\\xe5\\xba\\x9a\\xe7\\x8e\\x8b\\xe4\\xb8\\xbd\\xe5\\x9d\\xa4\\xe6\\x' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe5\xa4\xa7\xe5\xae\xb6\xe5\xb8\xae\xe5\xbf\x99\xe6\x89\xbe\xe6\x89\xbe\xe8\xbf\x99\xe6\x9d\xa1\xe7\xba\xa2\xe8\x89\xb2\xe7\x9f\xad\xe8\xa3\xa4']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe8\xbf\x99\xe6\x9d\xa1\xe8\xa3\xa4\xe5\xad\x90\xe6\x98\xaf\xe4\xbb\x80\xe4\xb9\x88\xe7\x89\x8c\xe5\xad\x90']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\xb1\\x82\\xe5\\x90\\x8c\\xe6\\xac\\xbe', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x9c\x89\xe4\xba\xba\xe7\x9f\xa5\xe9\x81\x93\xe5\x90\x97\xef\xbc\x9f\xef\xbc\x9f']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\xb1\\x82\\xe5\\x90\\x8c\\xe6\\xac\\xbe', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe8\\xbf\\x99\\xe5\\x8f\\x8c\\xe9\\x9e\\x8b\\xe5\\x90\\x8c\\xe6\\xac\\xbe ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe8\xbf\x99\xe5\x8f\x8c\xe9\x9e\x8b\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe8\\xbf\\x99\\xe5\\x8f\\x8c\\xe9\\x9e\\x8b\\xe5\\x90\\x8c\\xe6\\xac\\xbe ', '\\r\\n\\t\\t', '\\r\\' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe8\\xbf\\x99\\xe4\\xb8\\xaa\\xe6\\x98\\xaf\\xe9\\x99\\x88\\xe6\\x84\\x8f\\xe6\\xb6\\xb5\\xe7\\x9a\\x84\\xe4\\xb8\\x80\\xe4\\xb8\\xaa\\xe5\\x8c\\x85\\xef\\xbc\\x8c\\xe4\\xb8\\xaa\\xe4\\xba\\xba\\xe7\\x94\\xa8\\xe7\\x9a\\x84\\xef\\xbc\\x8c\\xe8\\xb0\\x81\\xe7\\x9f\\xa5\\xe9\\x81\\x93\\xe4\\xbb\\x80\\xe4\\xb9\\x88\\xe7\\x89\\x8c\\xe5\\xad\\x90\\xef\\xbc\\x8c\\xe5\\x93\\xaa\\xe9\\x87\\x8c\\xe5\\x8f\\xaf\\xe4\\xbb\\xa5\\xe4\\xb9\\xb0\\xe5\\x90\\x97\\xef\\xbc\\x9f ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x88\x91\xe7\x9a\x84\xe5\xb8\x8c\xe6\x9c\x9b']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe8\\xbf\\x99\\xe4\\xb8\\xaa\\xe6\\x98\\xaf\\xe9\\x99\\x88\\xe6\\x84\\x8f\\xe6\\xb6\\xb5\\xe7\\x9a' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe8\xbf\x99\xe8\xa3\x99\xe5\xad\x90\xe4\xbb\x80\xe4\xb9\x88\xe5\x93\x81\xe7\x89\x8c\xef\xbc\x9f']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[[' ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe4\xbd\x8e\xe4\xbb\xb7\xe5\x87\xba\xe5\x94\xaeS\xe5\xb0\x8f\xe5\xa7\x90\xe7\xba\xa4\xe4\xbd\x93']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe9\\x83\\x91\\xe7\\xa7\\x80\\xe6\\x99\\xb6\\xe6\\xac\\xbe\\xe5\\x81\\x9a\\xe7\\x9a\\x84\\xe6\\xaf\\x94\\xe8\\xbe\\x83\\xe5\\xa4\\x9a\\xef\\xbc\\x8c\\xe6\\x9c\\x89\\xe4\\xba\\x9b\\xe5\\x8f\\xaf\\xe5\\xae\\x9a\\xe5\\x88\\xb6\\xe6\\x9c\\x89\\xe4\\xba\\x9b\\xe4\\xb8\\x8d\\xe5\\xae\\x9a\\xe5\\x88\\xb6 \\xe5\\xa4\\xaa\\xe9\\x98\\xb3\\xe5\\x8f\\xaf\\xe9\\x95\\x87\\xe5\\xbe\\x97\\xe4\\xbd\\x8f\\xe6\\xa5\\xbc ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x98\x8e\xe6\x98\x9f\xe5\x90\x8c\xe6\xac\xbe\xe5\x8f\xaf\xe5\xae\x9a\xe5\x81\x9a(\xe0\xb9\x91\xe2\x80\xa2\xcc\x80\xe3\x85\x82\xe2\x80\xa2..']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe9\\x83\\x91\\xe7\\xa7\\x80\\xe6\\x99\\xb6\\xe6\\xac\\xbe\\xe5\\x81\\x9a\\xe7\\x9a\\x84\\xe6\\xaf' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x98\x8e\xe6\x98\x9f\xe5\x90\x8c\xe6\xac\xbe\xef\xbc\x8c\xe6\xbd\xae\xe6\xb5\x81\xe6\x90\xad\xe9\x85\x8d\xe5\xa4\xa7\xe8\x8c\x83\xe5\x84\xbf\xef\xbc\x81\xe6\x89\xab\xe6\x88\x91\xe5\xa4\xb4\xe5\x83\x8f\xe5\x93\xa6~\xe5\x95\xa5\xe9\x83\xbd\xe6\x9c\x89']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\xb8\xae\xe5\xbf\x99\xe6\x89\xbe\xe8\xbf\x99\xe4\xb8\xaat\xe6\x81\xa4']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[[' ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe8\xb0\x81\xe6\x9c\x89\xe8\xbf\x99\xe4\xbb\xb6\xe7\x88\xb1\xe6\x83\x85\xe5\x9b\x9e\xe6\x9d\xa5\xe4\xba\x86\xe5\x8c\x85\xe5\xbf\xb5\xe5\xbf\xb5\xe7\x9a\x84\xe7\xba\xa2\xe8\x89\xb2\xe8\xa1\xa3\xe6\x9c\x8d\xe5\x95\x8a']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\xb1\x82\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['iu\\xe6\\x9d\\x8e\\xe6\\x99\\xba\\xe6\\x81\\xa9 \\xe9\\x9f\\xa9\\xe5\\x89\\xa7\\xe5\\x88\\xb6\\xe4\\xbd\\x9c\\xe4\\xba\\xba \\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe6\\x9c\\x89\\xe6\\xb2\\xa1\\xe6\\x9c\\x89']]",
	 'quizeTitle': ['iu\xe6\x9d\x8e\xe6\x99\xba\xe6\x81\xa9   \xe9\x9f\xa9\xe5\x89\xa7\xe5\x88\xb6\xe4\xbd\x9c\xe4\xba\xba']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'iu\\xe6\\x9d\\x8e\\xe6\\x99\\xba\\xe6\\x81\\xa9 \\xe9\\x9f\\xa9\\xe5\\x89\\xa7\\xe5\\x88\\xb6\\xe4\\' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe7\\x9c\\x8b\\xe5\\xbe\\x88\\xe5\\xa4\\x9a\\xe6\\x9c\\x8b\\xe5\\x8f\\x8b\\xef\\xbc\\x8c\\xe9\\x83\\xbd\\xe5\\x9c\\xa8\\xe6\\x89\\xbe\\xe6\\x98\\x8e\\xe6\\x98\\x9f\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xef\\xbc\\x8c\\xe4\\xba\\x8e\\xe6\\x98\\xaf\\xe6\\x88\\x91\\xe5\\x81\\x9a\\xe4\\xba\\x86\\xe4\\xb8\\x80\\xe4\\xb8\\xaa\\xe6\\x98\\x8e\\xe6\\x98\\x9f\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe7\\xbd\\x91\\xe7\\xab\\x99\\xe3\\x80\\x82 \\xe6\\x8a\\x8a\\xe5\\xbe\\x88\\xe5\\xa4\\x9a\\xe6\\x98\\x8e\\xe6\\x98\\x9f\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe9\\x83\\xbd\\xe6\\x90\\x9e\\xe5\\x88\\xb0\\xe7\\xbd\\x91\\xe7\\xab\\x99\\xe4\\xba\\x86 \\xef\\xbc\\x8c\\xe5\\x9b\\xa0\\xe4\\xb8\\xba\\xe6\\x97\\xb6\\xe9\\x97\\xb4\\xe5\\x85\\xb3\\xe7\\xb3\\xbb\\xef\\xbc\\x8c\\xe8\\xbf\\x98\\xe4\\xb8\\x8d\\xe6\\x98\\xaf\\xe5\\xbe\\x88\\xe5\\x85\\xa8\\xe3\\x80\\x82\\xe6\\xbb\\xa1\\xe8\\xb6\\xb3\\xe4\\xb8\\x8d\\xe4\\xba\\x86\\xe5\\xa4\\xa7\\xe5\\xae\\xb6\\xe7\\x9a\\x84\\xe9\\x9c\\x80\\xe8\\xa6\\x81\\xe3\\x80\\x82\\xe4\\xbd\\x86\\xe6\\x98\\xaf\\xe6\\x88\\x91\\xe4\\xbc\\x9a', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe3\x80\x90\xe5\x90\x8c\xe6\xac\xbe\xe3\x80\x91[2014.9.26] \xe7\x88\xb1\xe6\x98\x8e\xe6\x98\x9f\xe5\x90\x8c\xe6\xac\xbe\xe5\xa4\xa7\xe5\x85\xa8']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe7\\x9c\\x8b\\xe5\\xbe\\x88\\xe5\\xa4\\x9a\\xe6\\x9c\\x8b\\xe5\\x8f\\x8b\\xef\\xbc\\x8c\\xe9\\x83' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe4\\xbd\\xa0\\xe5\\x8f\\xaf\\xe4\\xbb\\xa5\\xe5\\x8f\\x91\\xe6\\xb8\\x85\\xe6\\x99\\xb0\\xe7\\x9a\\x84\\xe7\\x85\\xa7\\xe7\\x89\\x87\\xe7\\xbb\\x99\\xe6\\x88\\x91\\xe6\\x9c\\x80\\xe5\\xa5\\xbd\\xe6\\x98\\xaf\\xe6\\xad\\xa3\\xe9\\x9d\\xa2\\xef\\xbc\\x8c\\xe6\\x9c\\x89\\xe6\\x98\\x8e\\xe6\\x98\\x9f\\xe5\\x90\\x8d\\xe5\\xad\\x97\\xe7\\x9a\\x84\\xe6\\x9c\\x80\\xe5\\xa5\\xbd\\xe4\\xb9\\x9f\\xe5\\x91\\x8a\\xe8\\xaf\\x89\\xe6\\x88\\x91\\xe3\\x80\\x82\\xe6\\x9c\\x89\\xe6\\x97\\xb6\\xe4\\xb8\\x8d\\xe5\\x9c\\xa8\\xe8\\xb4\\xb4\\xe5\\x90\\xa7\\xef\\xbc\\x8c\\xe8\\xaf\\xb7\\xe5\\x8a\\xa0\\xe6\\x88\\x912011074697\\xe6\\x88\\x91\\xe7\\x9a\\x84\\xe6\\x89\\xa3\\xe6\\x89\\xa3 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x98\x8e\xe6\x98\x9f\xe5\x90\x8c\xe6\xac\xbe\xe4\xbd\xa0\xe6\x89\xbe\xe6\x88\x91\xe5\xb0\xb1\xe5\xaf\xb9\xe4\xba\x86']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe4\\xbd\\xa0\\xe5\\x8f\\xaf\\xe4\\xbb\\xa5\\xe5\\x8f\\x91\\xe6\\xb8\\x85\\xe6\\x99\\xb0\\xe7\\x9a' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe7\\x94\\xb7\\xe7\\xa5\\x9e\\xe9\\x95\\x87\\xe6\\xa5\\xbc ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe5\xb8\xae\xe6\x89\xbe\xe6\x98\x8e\xe6\x98\x9f\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe7\\x94\\xb7\\xe7\\xa5\\x9e\\xe9\\x95\\x87\\xe6\\xa5\\xbc ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\' at line 1")
	
2015-06-17 00:48:40+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe7\\x95\\x99\\xe8\\xa8\\x80\\xe6\\x88\\x96\\xe8\\x80\\x85\\xe7\\xa7\\x81\\xe4\\xbf\\xa1\\xe9\\x97\\xae\\xe4\\xbb\\xb7 \\xe9\\x83\\xbd\\xe6\\x98\\xaf\\xe6\\xad\\xa3\\xe5\\x93\\x81 \\xe4\\xb8\\x8d\\xe7\\x9b\\xb8\\xe4\\xbf\\xa1\\xe7\\x9a\\x84\\xe5\\x88\\xab\\xe6\\x9d\\xa5 ', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe3\x80\x90\xe5\x90\x8c\xe6\xac\xbe\xe3\x80\x91\xe4\xb8\x96\xe5\x8b\x8bSEHUN  \xe7\xa7\x80\xe6\x99\xb6krystal\xe5\x90\x8c\xe6\xac\xbe']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe7\\x95\\x99\\xe8\\xa8\\x80\\xe6\\x88\\x96\\xe8\\x80\\x85\\xe7\\xa7\\x81\\xe4\\xbf\\xa1\\xe9\\x97' at line 1")
	
2015-06-17 00:48:40+0800 [wa] DEBUG: Scraped from <200 http://tieba.baidu.com/f?kw=%E6%98%8E%E6%98%9F%E5%90%8C%E6%AC%BE&ie=utf-8&pn=0>
	{'quizeContent': '[[]]',
	 'quizeTitle': ['\xe4\xb8\x80\xe4\xb8\xaa\xe5\x90\x8a\xe8\xa3\x86\xe8\xa3\xa4  \xe5\xb1\x81\xe8\x82\xa1\xe7\x9a\x84\xe6\xad\xa3\xe4\xb8\xad\xe9\x97\xb4\xe6\x98\xaf\xe4\xb8\x80\xe4\xb8\xaa\xe5\xa4\xa7\xe2\x9d\x8c \xe6\x98\xaf\xe4\xbb\x80\xe4\xb9\x88\xe7\x89\x8c\xe5\xad\x90\xe5\x95\x8a']}
2015-06-17 00:48:41+0800 [wa] ERROR: Error processing {'quizeContent': "[['\\xe6\\x9c\\x80\\xe8\\xbf\\x91\\xe5\\x88\\x98\\xe9\\x9b\\xaf\\xe8\\xb6\\x8a\\xe6\\x9d\\xa5\\xe8\\xb6\\x8a\\xe7\\x81\\xab\\xe4\\xba\\x86\\xef\\xbc\\x81\\xe4\\xbd\\x86\\xe6\\x98\\xaf\\xe6\\x88\\x91\\xe8\\xa7\\x89\\xe5\\xbe\\x97\\xe8\\xbf\\x99\\xe4\\xb8\\xaa\\xe5\\xa6\\xb9\\xe5\\xad\\x90\\xe7\\x9a\\x84\\xe7\\xa9\\xbf\\xe6\\x90\\xad\\xe6\\x88\\x91\\xe7\\x9c\\x9f\\xe7\\x9a\\x84\\xe5\\xa5\\xbd\\xe5\\x96\\x9c\\xe6\\xac\\xa2\\xef\\xbc\\x81\\xef\\xbc\\x81 \\xe4\\xb8\\x8a\\xe6\\xb7\\x98\\xe5\\xae\\x9d\\xe6\\x8b\\xbc\\xe5\\x91\\xbd\\xe6\\x90\\x9c\\xe5\\x90\\x8c\\xe6\\xac\\xbe\\xe6\\x90\\x9c\\xe7\\xb1\\xbb\\xe4\\xbc\\xbc\\xe9\\x83\\xbd\\xe6\\x90\\x9c\\xe4\\xb8\\x8d\\xe5\\x88\\xb0\\xe3\\x80\\x82\\xe3\\x80\\x82\\xe6\\x90\\x9c\\xe5\\x88\\xb0\\xe7\\x9a\\x84\\xe8\\xb4\\xa8\\xe9\\x87\\x8f\\xe5\\x8f\\x88\\xe4\\xb8\\x8d\\xe5\\xa4\\xaa\\xe5\\xa5\\xbd\\xe3\\x80\\x82\\xe3\\x80\\x82\\xe3\\x80\\x82\\xe3\\x80\\x82\\xe3\\x80\\x82\\xe3\\x80\\x82\\xe4\\xb8\\x89\\xe4\\xba\\x94\\xe5\\x8d\\x81\\xe5\\x9d\\x97\\xe7\\x9a\\x84\\xe4\\xb8\\x9c\\xe8\\xa5\\xbf', '\\r\\n\\t\\t', '\\r\\n\\t', '\\r\\n\\t\\t', '\\r\\n\\t'], [u'http://tb2.bdstatic.com/tb/static-frs/img/blankwhite_120.gif?v=1']]",
	 'quizeTitle': ['\xe6\x89\xbe\xe5\x90\x8c\xe6\xac\xbe\xef\xbc\x8c\xe5\x85\xb6\xe5\xae\x9e\xe5\xb0\xb1\xe6\x98\xaf\xe8\xbf\x99\xe4\xb9\x88\xe7\xae\x80\xe5\x8d\x95\xef\xbc\x81see\xe4\xb8\x80see\xe5\x88\x98\xe9\x9b\xaf\xe7\x9a\x84fashion']}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/root/stczwd/Scrapy/wa/wa/pipelines.py", line 54, in process_item
	    cur.execute(sql)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
	    self.errorhandler(self, exc, value)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
	    raise errorclass, errorvalue
	_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\xe6\\x9c\\x80\\xe8\\xbf\\x91\\xe5\\x88\\x98\\xe9\\x9b\\xaf\\xe8\\xb6\\x8a\\xe6\\x9d\\xa5\\xe8\\xb6' at line 1")
	
2015-06-17 00:48:41+0800 [wa] INFO: Closing spider (finished)
2015-06-17 00:48:41+0800 [wa] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 269,
	 'downloader/request_count': 1,
	 'downloader/request_method_count/GET': 1,
	 'downloader/response_bytes': 61785,
	 'downloader/response_count': 1,
	 'downloader/response_status_count/200': 1,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 6, 16, 16, 48, 41, 6672),
	 'item_scraped_count': 3,
	 'log_count/DEBUG': 6,
	 'log_count/ERROR': 48,
	 'log_count/INFO': 7,
	 'response_received_count': 1,
	 'scheduler/dequeued': 1,
	 'scheduler/dequeued/memory': 1,
	 'scheduler/enqueued': 1,
	 'scheduler/enqueued/memory': 1,
	 'start_time': datetime.datetime(2015, 6, 16, 16, 48, 40, 409902)}
2015-06-17 00:48:41+0800 [wa] INFO: Spider closed (finished)
